name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler: 2.2.15
        bundler-cache: true
    - name: Install Ruby deps
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run RSpec
      run: |
        bundle exec rake spec
