name: RSpec

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.2.15
        # bundler-cache: true
    - name: Install Ruby deps
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run Ruby Next
      run:  |
        bundle exec rake nextify
    - name: Run RSpec
      run: |
        bundle exec rake spec
